"""go

Revision ID: 6c07dd20a647
Revises: 
Create Date: 2024-06-23 19:35:12.003996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c07dd20a647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathogen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('schema', sa.String(length=255), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathogen_deleted_at'), 'pathogen', ['deleted_at'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.String(length=255), nullable=False),
    sa.Column('pathogen_id', sa.UUID(), nullable=False),
    sa.Column('admin_group', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pathogen_id'], ['pathogen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_deleted_at'), 'project', ['deleted_at'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('admin_group', sa.String(length=255), nullable=True),
    sa.Column('member_group', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_deleted_at'), 'study', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_deleted_at'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_project_deleted_at'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_pathogen_deleted_at'), table_name='pathogen')
    op.drop_table('pathogen')
    # ### end Alembic commands ###
