# Use the official Python image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /projects-service/app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn

# Copy the local code to the container image (comment this out since we're mounting the volume)
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run the application
CMD ["uvicorn", "--app-dir", "/projects-service/app/app", "--port", "5000", "app:app"]
